name: Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  deploy-Core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Add nuget source
        run: dotnet nuget add source "https://nuget.pkg.github.com/Cteso/index.json" --name "github" --username "Cteso" --password ${{ secrets.NUGET_SOURCE_API_KEY }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration release
      - name: Print git tag
        run: git describe --tags
      - name: Pack
        run: dotnet pack --configuration release --no-build --verbosity normal
      - name: Push ModbusTCP.NET
        run: cd ./ModbusTCP/bin/Release/ && dotnet nuget push "*.nupkg" --source "github" --skip-duplicate
